### ISSUE TITLE
Support the `MOC` set.

### ISSUE THREAD

**Issue by Sylk** [mtgenius/planechase#53]
Would you be able to add the new planes that came out?

**Comment by quisido** [comment]
I'm super interested in doing this; thanks for bringing it to my attention.

It's just a matter of time, as I have some personal priorities at the moment.

Is it only [these two](https://scryfall.com/search?q=type%3Aplane+set%3Amoc&unique=cards&as=grid&order=released&dir=desc) from the `MOC` set? Or are there other planes that are not yet present on Scryfall?

**Comment by Sylk** [comment]
Just those two from what I can tell. Just double checked.

**Comment by quisido** [comment]
I'm working on this now. It will take a little time as I modernize the code base. I'll update this issue when it's complete.

Thanks again for bringing it to my attention. I wasn't aware anyone was using this app, so it's validating to know the effort isn't wasted. 😁

**Comment by Sylk** [comment]
Turns out it was just one, The Isle of Vesuva was a reprint. #54

**Comment by quisido** [comment]
Sorry for the delay on this. It was difficult to find time, but I was determined to finish it this weekend. Please report any bugs, as this was a complete rewrite. I'd like to believe I am perfect and can't cause a regression, but with how much code was rewritten, it is possible that some user journeys weren't maintained. Let me know if that ends up being the cause. 👍

**Comment by Sylk** [comment]
> 

Rock solid re-write lad. Well done.
